kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: local-pvc
  namespace: nginx2
spec:
  accessModes: 
   - ReadWriteOnce
  resources:
     requests: 
        storage: 1Gi
  storageClassName: local-storage    

